require("nvim-treesitter.install").compilers = { "gcc" }

require("nvim-treesitter.configs").setup {
    ensure_installed = {
        "bash",
        "c",
        "caddy",
        "cmake",
        "cpp",
        "css",
        "csv",
        "cuda",
        "diff",
        "dockerfile",
        "fennel",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gpg",
        "graphql",
        "helm",
        "html",
        "java",
        "javadoc",
        "javascript",
        "jinja",
        "jinja_inline",
        "jq",
        "json",
        "jsonc",
        "julia",
        "just",
        "latex",
        "llvm",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "mlir",
        "nginx",
        "nix",
        "nu",
        "passwd",
        "perl",
        "python",
        "robots",
        "ruby",
        "rust",
        "scala",
        "scheme",
        "sql",
        "ssh_config",
        "svelte",
        "swift",
        "terraform",
        "thrift",
        "tmux",
        "tsx",
        "typescript",
        "xml",
        "yaml",
        "zig"
    },
    highlight = {
        enable = true, -- false will disable the whole extension
    },
    indent = {
        enable = true,
    },
}
